import numpy as np


class WindTurbine:
  ''' Class representing a DC wind turbine in a microgrid system.
  
  Args:
    cost_per_kw (:type:`float`): Cost of the wind turbine per unit of rated power in [$/kW].
    rated_power (:type:`float`): Rated power of the combined wind turbines in [kW].
    rated_wind_speed (:type:`float`): The rated wind speed in [m/s].
    cut_in (:type:`float`): The cut in speed in [m/s].
    cut_out (:type:`float`): The cut out speed in [m/s].
    height (:type:`float`): The wind turbine hub height in [m].
    lifetime (:type:`float`): The wind turbine lifetime in time intervals.
    resale_rate (:type:`float`): The resale rate of the wind turbines in [decimal].
  '''

  def __init__(self,
               cost_per_kw: float,
               rated_power: float = 5,
               rated_wind_speed: float = 12.5,
               cut_in: float = 3,
               cut_out: float = 20,
               height: float = 30,
               lifetime: float = 24,
               resale_rate: float = 0.75):
    
    self.cost_per_kw: float
    ''' Cost of the wind turbine per unit of rated power in [$/kW]. '''
    self.rated_power: float
    ''' Rated power of the wind turbine in [kW]. '''
    self.rated_wind_speed: float
    ''' The rated wind speed in [m/s]. '''
    self.cut_in: float
    ''' The cut in speed in [m/s]. '''
    self.cut_out: float
    ''' The cut out speed in [m/s]. '''
    self.height: float
    ''' The wind turbine hub height in [m]. '''
    self.lifetime: float
    ''' The wind turbines lifetime in time intervals. '''
    self.resale_rate: float
    ''' The resale rate of the wind turbines in [decimal]. '''
    self.output_power: np.typing.NDArray[np.floating]
    ''' Numpy array to store the output power generated by the wind turbines in kW. Default is ``None``. '''
    self.meet_demand: np.typing.NDArray[np.floating]
    ''' Energy that will effectively meet demand in [kWh]. Default is ``None``. '''

    self.cost_per_kw = cost_per_kw
    self.rated_power = rated_power
    self.rated_wind_speed = rated_wind_speed
    self.cut_in = cut_in
    self.cut_out = cut_out
    self.height = height
    self.lifetime = lifetime
    self.resale_rate = resale_rate

  def initialize(self, hours: int) -> None:
    ''' Initializes the components of the wind turbine.

    Args:
      hours (:type:`int`): Number of hours in the simulation.
    '''

    self.output_power = np.zeros(hours)
    self.meet_demand = np.zeros(hours)
  
  def generate_power(self, wind_speed: np.typing.NDArray[np.floating], height_reference: float) -> None:
    r'''Generates the output power for the entire wind turbine system using a cubic interpolation model.

    The power curve model is defined as:

    .. math::

        P(v) =
        \begin{cases}
          0, & v < v_{ci}; \\
          P_{rated} \cdot \left(\frac{v^3 - v_{ci}^3}{v_{rated}^3 - v_{ci}^3}\right), & v_{ci} \leq v < v_{rated}; \\
          P_{rated}, & v_{rated} \leq v \leq v_{co}; \\
          0, & v > v_{co}.
        \end{cases}

    Where:

    - :math:`v` is the wind speed at the hub height in [m/s];
    - :math:`v_{ci}` is the cut-in wind speed in [m/s];
    - :math:`v_{rated}` is the rated wind speed in [m/s];
    - :math:`v_{co}` is the cut-out wind speed in [m/s];
    - :math:`P_{rated}` is the total rated power of all turbines combined [kW].

    Args:
        wind_speed (:type:`np.typing.NDArray[np.floating]`): A numpy array with the wind speed measurements at the reference height.
        height_reference (:type:`float`): The height where the wind speed was measured in [m].
    '''

    # Apply the power law
    alpha = 1 / 7  # Hellman exponent (default value)
    wind_speed_hub = wind_speed * (self.height / height_reference) ** alpha
    # Calculate the output power using power curve
    cubic_mask = (self.cut_in <= wind_speed_hub) & (wind_speed_hub < self.rated_wind_speed)
    turbine_power = self.rated_power * (wind_speed_hub[cubic_mask]**3 - self.cut_in**3)/(self.rated_wind_speed**3 - self.cut_in**3)
    self.output_power[cubic_mask] = turbine_power
    rated_mask = (self.rated_wind_speed <= wind_speed_hub) & (wind_speed_hub <= self.cut_out)
    self.output_power[rated_mask] = self.rated_power

  
  def economic_analysis(self,
                        project_lifetime_intervals: np.typing.NDArray[np.integer],
                        maintenance_cost_rate: float,
                        discount_rate: float,
                        CRF: float) -> float:
    r''' Performs the economic analysis of the wind turbine using the Net Present Cost (NPC) approach.

    The total NPC of the wind turbines is given by:

    .. math::
        NPC = \text{IC} + \text{NPV}_{om} + \text{NPV}_{repl} - \text{NPV}_{sv}.

    Where:
    
    - :math:`\text{IC}` is the installation cost;
    - :math:`\text{NPV}_{om}` is the Net Present Value of annual operation and maintenance costs;
    - :math:`\text{NPV}_{repl}` is the Net Present Value of replacement costs during the project lifetime;
    - :math:`\text{NPV}_{sv}` is the Net Present Value of the resale value (salvage value) of the wind turbines at the end of their useful life.

    The installation cost is calculated as:

    .. math::
        \text{IC} = C_{kw} \cdot P_{rated}.

    :math:`C_{kw}` is the cost per kW of nominal capacity for the wind turbines and :math:`P_{rated}` is the rated power of the wind turbines. The operation and maintenance costs are calculated as:

    .. math::
        \text{NPV}_{om} = \sum^{T}_{t=1}\frac{\text{IC} \cdot \tau_{om}}{(1 + d)^t}.

    :math:`T` is the project lifetime in time intervals, :math:`d` is the discount rate per interval (assumed to be constant) in [decimal] and :math:`\tau_{om}` is the operation and maintenance cost rate in [decimal]. The replacement costs occur every :attr:`lifetime` intervals and are equal to the installation cost, discounted to present value according to the following equation:
    
    .. math::
      \text{NPV}_{repl} = \sum^{T}_{t=1}\frac{\left(\left\lfloor \frac{t}{T_{\text{repl}}} \right\rfloor - \left\lfloor \frac{t-1}{T_{\text{repl}}} \right\rfloor\right) \cdot \text{IC}}{(1 + d)^t},

    where :math:`T_{repl} = I^{\text{lifetime}}` is the time when the equipment must be replaced. The salvage value is calculated as:

    .. math::
      \text{NPV}_{sv} = \frac{\text{IC} \cdot \tau_{sv} \cdot T_{\text{remaining}}}{(1 + d)^T},

    where :math:`\tau_{sv}` is the resale rate of the wind turbines in [decimal] and :math:`T_{\text{remaining}}` is the remaining lifetime of the wind turbines in [decimal].

    Args:
        project_lifetime_intervals (:type:`np.typing.NDArray[np.integer]`): Intervals of project lifetime.
        maintenance_cost_rate (:type:`float`): Operation and maintenance cost rate based on installation costs in [decimal].
        discount_rate (:type:`float`): Discount rate (per interval) during the project lifetime in [decimal].
        CRF (:type:`float`): Capital Recovery Factor (CRF) during the project lifetime in [decimal].

    Returns:
        :type:`float`: Total Net Present Cost of the wind turbines in present value in [$].
    '''
    
    # Installation cost (CAPEX)
    installation_cost = self.cost_per_kw * self.rated_power
    NPC = installation_cost
    # O&M costs (discounted)
    NPC += (installation_cost * maintenance_cost_rate) / CRF
    # Replacement costs (discounted)
    n_repl = np.floor(project_lifetime_intervals / self.lifetime)
    NPC += np.sum(installation_cost * (n_repl[1:] - n_repl[:-1]) / ((1 + discount_rate) ** project_lifetime_intervals[1:]))
    # Resale | salvage value (discounted)
    project_lifetime = project_lifetime_intervals[-1]
    remaining_lifetime = 1 - (project_lifetime % self.lifetime) / self.lifetime
    NPC -= (installation_cost * self.resale_rate * remaining_lifetime) / ((1 + discount_rate) ** project_lifetime_intervals[-1])
    return float(NPC)
