import numpy as np
import numpy.typing as npt

class PhotovoltaicPanel:
  ''' Class representing a DC photovoltaic panel in a microgrid system.
  
  Args:
    cost_per_kwp (:type:`int | float`): Photovoltaic panels cost per kWp installed in [$/kWp].
    rated_power (:type:`int | float`): The maximum power output of the photovoltaic panels in [kW].
    lifetime (:type:`int | float`): The photovoltaic panels lifetime in time intervals.
  
  Raises:
    TypeError: If the input is not the expected type.
    ValueError: If the input is not the allowed value.
  '''

  def __init__(self,
               cost_per_kwp: int | float,
               rated_power: int | float = 30,
               lifetime: int | float = 20):
    
    self.cost_per_kwp: int | float
    ''' Photovoltaic panel cost per kWp installed in [$/kWp]. '''
    self.rated_power: int | float
    ''' Maximum power output of the photovoltaic panel in [kW]. '''
    self.lifetime: int | float
    ''' The photovoltaic panel lifetime in time intervals. '''
    self.output_power: npt.NDArray[np.floating]
    ''' Output power generated by the photovoltaic panels in [kW]. Default value is ``None``. '''
    self.meet_demand: npt.NDArray[np.floating]
    ''' Energy that will effectively meet demand in [kWh]. Default is ``None``. '''

    self.cost_per_kwp = cost_per_kwp
    self.rated_power = rated_power
    self.lifetime = lifetime

  def initialize(self, hour_steps: int) -> None:
    ''' Initializes the components of the photovoltaic panel.

    Args:
      hour_steps (:type:`int`): Number of hour steps in the simulation.
    '''

    self.output_power = np.zeros(hour_steps)
    self.meet_demand = np.zeros(hour_steps)

  def generate_power(self, temperature: npt.NDArray[np.floating], solar_irradiance: npt.NDArray[np.floating]) -> None:
    r''' Generates the output power according to the following equation:
      
      .. math::
        P_{out} = P_{rated} \cdot \left(\frac{G}{G_{ref}}\right) \cdot (1 + K_t \cdot (T_c - T_{ref})).

      Where:
      
      - :math:`P_{out}` is the output power in [kW];
      - :math:`P_{rated}` is the rated power under reference conditions in [kW];
      - :math:`G` is the solar irradiance in [kW/m^2];
      - :math:`G_{ref}` is the solar irradiance at reference conditions in [kW/m^2];
      - :math:`K_t` is the power temperature coefficient of the photovoltaic panels in [1/ºC];
      - :math:`T_{amb}` is the ambient temperature in [ºC];
      - :math:`T_c` is the cell temperature in [ºC] estimated according to the following equation, considering :math:`NOCT = 45`:

        .. math::
          T_c = T_{amb} + \frac{NOCT - 20}{800} \cdot G.

      - :math:`T_{ref}` is the temperature at reference conditions in [ºC].
    
      Args:
        temperature (:type:`npt.NDArray[np.floating]`): Numpy array with the temperature in [ºC] at each hour.
        solar_irradiance (:type:`npt.NDArray[np.floating]`): Numpy array with the solar irradiance in [kW/m^2] at each hour.
    '''

    irradiance_ref = 1 # Reference irradiance [kW/m^2]
    temperature_ref = 25 # Reference temperature in [ºC]
    power_temperature_coefficient = 3.7e-3 # Power temperature coefficient of maximum power in [1/°C]
    cell_temperature = temperature + 0.03125 * solar_irradiance # Cell temperature
    self.output_power[:] = np.minimum(self.rated_power * (solar_irradiance/irradiance_ref) * (1 + power_temperature_coefficient*(cell_temperature - temperature_ref)), self.rated_power)

  def economic_analysis(self,
                        project_lifetime_intervals: npt.NDArray[np.integer],
                        maintenance_cost_rate: int | float,
                        discount_rate: int | float,
                        CRF: int |float) -> float:
    r''' Performs the economic analysis of the photovoltaic panels using the Net Present Cost (NPC) approach.

    The total NPC of the photovoltaic system is given by:

    .. math::
        NPC_{pv} = \text{IC}_{pv} + \text{NPV}_{om} + \text{NPV}_{repl}.

    Where:

    - :math:`\text{IC}_{pv}` is the installation cost;
    - :math:`\text{NPV}_{om}` is the Net Present Value of annual operation and maintenance costs;
    - :math:`\text{NPV}_{repl}` is the Net Present Value of replacement costs during the project lifetime.

    The installation cost is calculated as:

    .. math::
        \text{IC}_{pv} = C_{kwp} \cdot P_{rated}.

    :math:`C_{kwp}` is the cost per kWp of the photovoltaic panels and :math:`P_{rated}` is the rated power of the photovoltaic panel. The operation and maintenance costs are calculated as:

    .. math::
        \text{NPV}_{om} = \sum^{T}_{t=1}\frac{\text{IC}_{pv} \cdot \tau_{om}}{(1 + d)^t}.

    :math:`T` is the project lifetime in time intervals, :math:`d` is the discount rate per interval (assumed to be constant) in [decimal] and :math:`\tau_{om}` is the operation and maintenance cost rate in [decimal]. The replacement costs occur every :attr:`lifetime` intervals and are equal to the installation cost, discounted to present value according to the following equation:
    
    .. math::
      \text{NPV}_{repl} = \sum^{T}_{t=1}\frac{\left(\left\lfloor \frac{t}{T_{\text{repl}}} \right\rfloor - \left\lfloor \frac{t-1}{T_{\text{repl}}} \right\rfloor\right) \cdot \text{IC}_{pv}}{(1 + d)^t},

    where :math:`T_{repl} = I^{\text{lifetime}}_{\text{pv}}` is the time when the euipament must to be replaced.

    Args:
        project_lifetime_intervals (:type:`npt.NDArray[np.integer]`): Intervals of project lifetime.
        maintenance_cost_rate (:type:`int | float`): Operation and maintenance cost rate based on installation costs in [decimal].
        discount_rate (:type:`int | float`): Discount rate (per interval) during the project lifetime in [decimal].
        CRF (:type:`int | float`): Capital Recovery Factor (CRF) during the project lifetime in [decimal].

    Returns:
        :type:`float`: Total Net Present Cost of the photovoltaic components in present value in [$].
    '''

    # Installation cost (CAPEX)
    installation_cost = self.cost_per_kwp * self.rated_power
    NPC = installation_cost
    # O&M costs (discounted)
    NPC += (installation_cost * maintenance_cost_rate) / CRF
    # Replacement costs (discounted)
    n_repl = np.ceil(project_lifetime_intervals / self.lifetime)
    NPC += np.sum(installation_cost * (n_repl[1:] - n_repl[:-1]) / ((1 + discount_rate) ** project_lifetime_intervals[1:]))
    return float(NPC)
