import numpy as np

class PhotovoltaicPanel:
  ''' Class representing a DC photovoltaic panel in a microgrid system.
  
  Args:
    cost_per_kwp (:type:`int | float`): Photovoltaic panels cost per kWp installed in [US$/kWp].
    om_cost_rate (:type:`int | float`): Operation and maintenance cost rate for photovoltaic panels based on installation costs in [decimal].
    rated_power (:type:`int | float`): The maximum power output of the photovoltaic panels in [kW].
    lifetime (:type:`int | float`): The photovoltaic panels lifetime in [year].
  
  Raises:
    TypeError: If the input is not the expected type.
    ValueError: If the input is not the allowed value.
  '''

  def __init__(self,
               cost_per_kwp: int | float,
               om_cost_rate: int | float = 0.02,
               rated_power: int | float = 30,
               lifetime: int | float = 20):
    
    self.cost_per_kwp: int | float
    ''' Photovoltaic panel cost per kWp installed in [US$/kWp]. '''
    self.om_cost_rate: int | float
    ''' Operation and maintenance cost rate for photovoltaic panels based on installation costs in [decimal]. '''
    self.rated_power: int | float
    ''' Maximum power output of the photovoltaic panel in [kW]. '''
    self.lifetime: int | float
    ''' The photovoltaic panel lifetime in [year]. '''
    self.output_power: np.ndarray[np.float64] | None = None
    ''' Output power generated by the photovoltaic panels in [kW]. Default value is ``None``. '''
    self.meet_demand: np.ndarray[np.float64] | None = None
    ''' Energy that will effectively meet demand in [kWh]. Default is ``None``. '''

    self.cost_per_kwp = cost_per_kwp
    self.om_cost_rate = om_cost_rate
    self.rated_power = rated_power
    self.lifetime = lifetime

  def initialize(self, hour_steps: int) -> None:
    ''' Initializes the components of the photovoltaic panel.

    Args:
      hour_steps (:type:`int`): Number of hour steps in the simulation.
    '''

    self.output_power = np.zeros(hour_steps)
    self.meet_demand = np.zeros(hour_steps)

  def generate_power(self, temperature: np.ndarray[np.float64], solar_radiation: np.ndarray[np.float64]) -> None:
    r''' Generates the output power according to the following equation:
      
      .. math::
        P_{out} = P_{rated} \cdot \left(\frac{G}{G_{ref}}\right) \cdot (1 + K_t \cdot (T_c - T_{ref})).

      where:
      
      - :math:`P_{out}` is the output power in [kW];
      - :math:`P_{rated}` is the rated power under reference conditions in [kW];
      - :math:`G` is the solar radiation in [kW/m^2];
      - :math:`G_{ref}` is the solar radiation at reference conditions in [kW/m^2];
      - :math:`K_t` is the power temperature coefficient of the photovoltaic panels in [1/ºC];
      - :math:`T_{amb}` is the ambient temperature in [ºC];
      - :math:`T_c` is the cell temperature in [ºC] estimated according to the following equation, considering :math:`NOCT = 45`:

        .. math::
          T_c = T_{amb} + \frac{NOCT - 20}{800} \cdot G.

      - :math:`T_{ref}` is the temperature at reference conditions in [ºC].
    
      Args:
        temperature (:type:`np.ndarray[np.float64]`): Numpy array with the temperature in [ºC] at each hour.
        solar_radiation (:type:`np.ndarray[np.float64]`): Numpy array with the solar radiation in [kW/m^2] at each hour.
    '''

    irradiance_ref = 1 # Reference irradiance [kW/m^2]
    temperature_ref = 25 # Reference temperature in [ºC]
    power_temperature_coefficient = 3.7e-3 # Power temperature coefficient of maximum power in [1/°C]
    cell_temperature = temperature + 0.03125 * solar_radiation # Cell temperature
    self.output_power[:] = np.minimum(self.rated_power * (solar_radiation/irradiance_ref) * (1 + power_temperature_coefficient*(cell_temperature - temperature_ref)), self.rated_power)

  def economic_analysis(self, project_lifetime: int, discount_rate: int | float) -> float:
    r''' Performs the economic analysis of the photovoltaic panels using the Net Present Cost (NPC) approach.

    The total NPC of the photovoltaic system is given by:

    .. math::
        NPC_{PV} = IC_{PV} + NPV_{OM} + NPV_{repl}.

    Where:
      - :math:`IC_{PV}` is the installation cost;
      - :math:`NPV_{OM}` is the Net Present Value of annual operation and maintenance costs;
      - :math:`NPV_{repl}` is the Net Present Value of replacement costs during the project lifetime.

    The installation cost is calculated as:

    .. math::
        IC_{PV} = C_{kWp} \cdot P_{rated}.

    :math:`C_{kWp}` is the cost per kWp of the photovoltaic panels and :math:`P_{rated}` is the rated power of the photovoltaic panel. The operation and maintenance costs are assumed to be constant each year as a percentage of the installation cost:

    .. math::
        OM_{annual} = IC_{PV} \cdot \tau_{OM}.

    :math:`\tau_{OM}` is the operation and maintenance cost rate in [decimal]. The replacement costs occur every :attr:`lifetime` years and are equal to the installation cost,
    discounted to present value.

    Args:
        project_lifetime (:type:`int`): Total project lifetime in [years].
        discount_rate (:type:`int | float`): Discount rate (per year) during the project lifetime in [decimal].

    Returns:
        :type:`float`: Total Net Present Cost of the photovoltaic components in present value in [US$].
    '''
    
    years = np.arange(project_lifetime)
    # Installation cost (CAPEX)
    installation_cost = self.cost_per_kwp * self.rated_power
    # Installation cost (CAPEX) - year 0 only
    NPC = installation_cost
    # O&M costs (discounted)
    OM_cost = (self.om_cost_rate * installation_cost) / ((1 + discount_rate) ** years)
    NPC += np.sum(OM_cost)
    # Replacement costs (discounted)
    replacement_years = np.arange(self.lifetime, project_lifetime, self.lifetime)
    if len(replacement_years) > 0:
        NPV_repl = installation_cost / ((1 + discount_rate) ** replacement_years)
        NPC += np.sum(NPV_repl)
    return NPC
