import numpy as np

class WindTurbine:
  ''' Class representing a DC wind turbine in a microgrid system.
  
  Args:
    cost_per_kw (:type:`int | float`): Cost of the wind turbine per unit of rated power in [US$/kW].
    rated_power (:type:`int | float`): Rated power of the combined wind turbines in [kW].
    rated_wind_speed (:type:`int | float`): The rated wind speed in [m/s].
    cut_in (:type:`int | float`): The cut in speed in [m/s].
    cut_out (:type:`int | float`): The cut out speed in [m/s].
    height (:type:`int | float`): The wind turbine hub height in [m].
    lifetime (:type:`int | float`): The wind turbine lifetime in [year].

  Raises:
    TypeError: If the input is not the expected type.
    ValueError: If the input is not the allowed value.
  '''

  def __init__(self,
               cost_per_kw: int | float,
               rated_power: int | float = 5,
               rated_wind_speed: int | float = 12.5,
               cut_in: int | float = 3,
               cut_out: int | float = 20,
               height: int | float = 30,
               lifetime: int | float = 24):
    
    self.cost_per_kw: int | float
    ''' Cost of the wind turbine per unit of rated power in [US$/kW]. '''
    self.rated_power: int | float
    ''' Rated power of the wind turbine in [kW]. '''
    self.rated_wind_speed: int | float
    ''' The rated wind speed in [m/s]. '''
    self.cut_in: int | float
    ''' The cut in speed in [m/s]. '''
    self.cut_out: int | float
    ''' The cut out speed in [m/s]. '''
    self.height: int | float
    ''' The wind turbine hub height in [m]. '''
    self.lifetime: int | float
    ''' The wind turbines lifetime in [year]. '''
    self.operation_cost: float = 0.0
    ''' Total costs of the public grid during the operation simulation in [US$]. '''
    self.output_power: np.ndarray[np.float64] | None = None
    ''' Numpy array to store the output power generated by the wind turbines in kW. Default is ``None``. '''
    self.meet_demand: np.ndarray[np.float64] | None = None
    ''' Energy that will effectively meet demand in [kWh]. Default is ``None``. '''

    self.cost_per_kw = cost_per_kw
    self.rated_power = rated_power
    self.rated_wind_speed = rated_wind_speed
    self.cut_in = cut_in
    self.cut_out = cut_out
    self.height = height
    self.lifetime = lifetime

  def initialize(self, hour_steps: int) -> None:
    ''' Initializes the components of the wind turbine.

    Args:
      hour_steps (:type:`int`): Number of hour steps in the simulation.
    '''

    self.output_power = np.zeros(hour_steps)
    self.meet_demand = np.zeros(hour_steps)
  
  def generate_power(self, wind_speed: np.ndarray[np.float64], height_reference: int | float) -> None:
    r'''Generates the output power for the entire wind turbine system using a cubic interpolation model.

    The power curve model is defined as:

    .. math::

        P(v) =
        \begin{cases}
          0, & v < v_{ci}; \\
          P_{rated} \cdot \left(\frac{v^3 - v_{ci}^3}{v_{rated}^3 - v_{ci}^3}\right), & v_{ci} \leq v < v_{rated}; \\
          P_{rated}, & v_{rated} \leq v \leq v_{co}; \\
          0, & v > v_{co}.
        \end{cases}

    Where:
      - :math:`v` is the wind speed at the hub height in [m/s];
      - :math:`v_{ci}` is the cut-in wind speed in [m/s];
      - :math:`v_{rated}` is the rated wind speed in [m/s];
      - :math:`v_{co}` is the cut-out wind speed in [m/s];
      - :math:`P_{rated}` is the total rated power of all turbines combined [kW].

    Args:
        wind_speed (:type:`np.ndarray[np.float64]`): A numpy array with the wind speed measurements at the reference height.
        height_reference (:type:`int | float`): The height where the wind speed was measured in [m].
    '''

    # Applicate the power law
    alpha = 1 / 7  # Hellman exponent (default value)
    wind_speed_hub = wind_speed * (self.height / height_reference) ** alpha
    # Calculate the output power using power curve
    mask = (self.cut_in <= wind_speed_hub) & (wind_speed_hub <= self.cut_out)
    turbine_power = self.rated_power * (wind_speed_hub[mask]**3 - self.cut_in**3)/(self.rated_wind_speed**3 - self.cut_in**3)
    self.output_power[mask] = np.minimum(turbine_power, self.rated_power)

  
  def economic_analysis(self, project_lifetime: int | float, maintenance_cost_rate: int | float, discount_rate: int | float) -> float:
    r''' Performs the economic analysis of the wind turbine using the Net Present Cost (NPC) approach.

    The total NPC of the wind turbines is given by:

    .. math::
        NPC_{wt} = IC_{wt} + NPV_{om} + NPV_{repl}.

    Where:
      - :math:`IC_{wt}` is the installation cost;
      - :math:`NPV_{om}` is the Net Present Value of annual operation and maintenance costs;
      - :math:`NPV_{repl}` is the Net Present Value of replacement costs during the project lifetime.

    The installation cost is calculated as:

    .. math::
        IC_{wt} = C_{kw} \cdot P_{rated}.

    :math:`C_{kw}` is the cost per kW of nominal capacity for the wind turbines and :math:`P_{rated}` is the rated power of the wind turbines. The operation and maintenance costs are calculated as:

    .. math::
        NPV_{om} = \sum^{T-1}_{t=0}\frac{IC_{wt} \cdot \tau_{om}}{(1 + d)^t}.

    :math:`T` is the project lifetime in [years], :math:`d` is the discount rate per year (assumed to be constant) in [decimal] and :math:`\tau_{om}` is the operation and maintenance cost rate in [decimal]. The replacement costs occur every :attr:`lifetime` years and are equal to the installation cost, discounted to present value according to the following equation:
    
    .. math::
        NPV_{repl} = \sum_{t \in T_{repl}}\frac{IC_{wt}}{(1 + d)^t},

    where :math:`T_{repl}` is the set of replacement years.

    Args:
        project_lifetime (:type:`int | float`): Total project lifetime in [years].
        maintenance_cost_rate (:type:`int | float`): Operation and maintenance cost rate based on installation costs in [decimal].
        discount_rate (:type:`int | float`): Discount rate (per year) during the project lifetime in [decimal].

    Returns:
        :type:`float`: Total Net Present Cost of the wind turbines in present value in [US$].
    '''
    
    years = np.arange(project_lifetime)
    # Installation cost (CAPEX)
    installation_cost = self.cost_per_kw * self.rated_power
    # Installation cost (CAPEX) - year 0 only
    NPC = installation_cost
    # O&M costs (discounted)
    OM_cost = (installation_cost * maintenance_cost_rate) / ((1 + discount_rate) ** years)
    NPC += np.sum(OM_cost)
    # Replacement costs (discounted)
    replacement_years = np.arange(self.lifetime, project_lifetime, self.lifetime)
    if len(replacement_years) > 0:
        NPV_repl = installation_cost / ((1 + discount_rate) ** replacement_years)
        NPC += np.sum(NPV_repl)
    return NPC
